### ISSUE TITLE
File update notifications

### ISSUE THREAD

**Issue by pkej** [nrkno/tv-automation-quantel-gateway#6]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x ] question about how to use this project

* **Summary**

Hi,
I'm wondering if this library can be used to find clips that have been changed, e.g. it has been published, then re-edited and we need a signal to another system telling it there has been changes? Other system equals subtitling services.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by sparkpunkd** [comment]
All things are possible, but this is not so easy. It has to do with the way the CORBA layer works underneath. At the moment, the quantel gateway is a stateless CORBA client - it sends request, receives a response and passes that on. With development, it would be possible to upgrade the connection so that the gateway becomes a CORBA server and can receive updates from the ISA when clips change - but this is quite a bit of C++ work and makes the gateway stateful, ie. more complex.

What Sofie does to find the latest version of a clip is to always query by ClipGUID rather than ClipID and choose the clip with the most recent modified time that has media (is not a placeholder). The system keeps a list of _clips if interest_ and, for each of these, checks every minute to see if the media is still available and/or has been updated.
